name: CI
on:
  push:
    paths:
      - 'templates/**'
      - 'scripts/**'
      - 'requirements.txt'
      - '.github/workflows/ci.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'templates/**'
      - 'scripts/**'
      - 'requirements.txt'
      - '.github/workflows/ci.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Validate Files in templates directory
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run test
        run: |
          cd scripts/ && \
          bash ./test.sh

  auto-approve:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Auto Approve PR
      uses: actions/github-script@v7
      with:
       script: |
        github.rest.pulls.createReview({
          owner: context.repo.owner,
          repo: context.repo.repo,
          pull_number: context.issue.number,
          event: "APPROVE"
        })
