name: CI
on:
  push:
    paths:
      - 'templates/**'
      - 'scripts/**'
      - 'requirements.txt'
      - '.github/workflows/ci.yml'
    branches:
      - master
  pull_request:
    paths:
      - 'templates/**'
      - 'scripts/**'
      - 'requirements.txt'
      - '.github/workflows/ci.yml'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Validate Files in templates directory
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run test
        run: |
          cd scripts/ && \
          bash ./test.sh

  auto-approve:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"