name: Validate CloudFormation Templates
on:
  paths:
    - 'templates/**'
    - 'scripts/**'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Files in templates directory
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: cd scripts/ && bash ./test.sh
